[pr_description]
extra_instructions="""\
For the title, use the format [type]: [summary]
"""
publish_description_as_comment=true
generate_ai_title=true
use_description_markers=true

[pr_reviewer]
extra_instructions="""\
In the `possible issues` section, emphasize the following:
- Is the code logic efficient?
-
"""
inline_code_comments=true
require_score_review=true
require_can_be_split_review=true
num_code_suggestions="8"

[pr_code_suggestions]
extra_instructions="""\
Emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
-
"""
num_code_suggestions_per_chunk="10"
commitable_code_suggestions=true
suggestions_score_threshold="8"

[pr_add_docs]
docs_style="sphinx"

[pr_custom_prompt]
prompt= 1) Strongly typed WITHOUT using 'any' type. 2)Check for bugs, null pointers, while making the code faster and more efficient. 3) Use best practices in error handling and security. 4) Lastly clean up the code while strictly keeping the code original function and styles respectively.

