/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as aiAssessment from "../aiAssessment.js";
import type * as appointment from "../appointment.js";
import type * as authAware from "../authAware.js";
import type * as estimate from "../estimate.js";
import type * as message from "../message.js";
import type * as onGoingService from "../onGoingService.js";
import type * as roleBased from "../roleBased.js";
import type * as tenant from "../tenant.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  aiAssessment: typeof aiAssessment;
  appointment: typeof appointment;
  authAware: typeof authAware;
  estimate: typeof estimate;
  message: typeof message;
  onGoingService: typeof onGoingService;
  roleBased: typeof roleBased;
  tenant: typeof tenant;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
